# Generated by Django 5.1.15 on 2026-02-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'ordering': ['name'], 'verbose_name': 'Bruger', 'verbose_name_plural': 'Brugere'},
        ),
        migrations.AddField(
            model_name='systemuser',
            name='auth_method',
            field=models.CharField(choices=[('local', 'Lokal'), ('azure_ad', 'Azure AD')], default='local', help_text='Lokal = brugervælger. Azure AD = fremtidig SSO integration.', max_length=20, verbose_name='Autentificeringsmetode'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='azure_ad_object_id',
            field=models.CharField(blank=True, help_text='Udfyldes automatisk ved Azure AD sync.', max_length=36, verbose_name='Azure AD Object ID'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stilling'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Afdeling'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Navn'),
        ),
    ]
