# Generated by Django 5.1.15 on 2026-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Navn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enhed',
                'verbose_name_plural': 'Enheder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Feltnavn')),
                ('field_type', models.CharField(choices=[('text', 'Tekst'), ('number', 'Tal'), ('checkbox', 'Checkbox')], default='text', max_length=20, verbose_name='Felttype')),
                ('is_required', models.BooleanField(default=False, verbose_name='Påkrævet')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='Standardværdi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortering')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='entities.entity')),
            ],
            options={
                'verbose_name': 'Brugerdefineret felt',
                'verbose_name_plural': 'Brugerdefinerede felter',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('entity', 'name')},
            },
        ),
    ]
