# Generated by Django 5.1.15 on 2026-02-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Tekst'), ('number', 'Tal'), ('checkbox', 'Checkbox'), ('todolist', 'Todo-liste')], default='text', max_length=20, verbose_name='Felttype'),
        ),
    ]
