# Generated by Django 5.1.15 on 2026-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='show_on_overview',
            field=models.BooleanField(default=False, verbose_name='Vis på onboarding'),
        ),
    ]
