# Generated by Django 5.1.15 on 2026-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0001_initial'),
        ('templates_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_employee_name', models.CharField(max_length=300, verbose_name='Medarbejder navn')),
                ('new_employee_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('new_employee_department', models.CharField(blank=True, max_length=200, verbose_name='Afdeling')),
                ('new_employee_position', models.CharField(blank=True, max_length=300, verbose_name='Stilling')),
                ('start_date', models.DateField(help_text='Dato hvor den nye medarbejder starter', verbose_name='Startdato')),
                ('notes', models.TextField(blank=True, verbose_name='Noter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboardings', to='core.systemuser', verbose_name='Oprettet af')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='templates_mgmt.onboardingtemplate')),
            ],
            options={
                'verbose_name': 'Onboarding-proces',
                'verbose_name_plural': 'Onboarding-processer',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Afventer'), ('ready', 'Klar'), ('in_progress', 'I gang'), ('completed', 'Færdig'), ('skipped', 'Sprunget over')], default='pending', max_length=20, verbose_name='Status')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('deadline_overridden', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='core.systemuser', verbose_name='Ansvarlig')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='core.systemuser')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='onboarding.onboardingtask')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to='entities.entity')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.onboardingprocess')),
                ('source_template_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_mgmt.templateentity')),
            ],
            options={
                'verbose_name': 'Onboarding-opgave',
                'verbose_name_plural': 'Onboarding-opgaver',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTaskFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('value_checkbox', models.BooleanField(default=False)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.customfielddefinition')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='onboarding.onboardingtask')),
            ],
            options={
                'unique_together': {('task', 'field_definition')},
            },
        ),
        migrations.CreateModel(
            name='TaskNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=True)),
                ('send_in_app', models.BooleanField(default=True)),
                ('notify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='onboarding.onboardingtask')),
            ],
            options={
                'unique_together': {('task', 'notify_user')},
            },
        ),
    ]
