# Generated by Django 5.1.15 on 2026-02-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_systemuser_options_systemuser_auth_method_and_more'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasknotificationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tasknotificationrule',
            name='notify_assignee',
            field=models.BooleanField(default=False, verbose_name='Notificer ansvarlig'),
        ),
        migrations.AddField(
            model_name='tasknotificationrule',
            name='trigger_status',
            field=models.CharField(choices=[('ready', 'Klar'), ('in_progress', 'I gang'), ('completed', 'Færdig'), ('skipped', 'Sprunget over')], default='completed', max_length=20, verbose_name='Ved status'),
        ),
        migrations.AlterField(
            model_name='tasknotificationrule',
            name='notify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.systemuser'),
        ),
    ]
