# Generated by Django 5.1.15 on 2026-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Navn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding-skabelon',
                'verbose_name_plural': 'Onboarding-skabeloner',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_start', models.PositiveIntegerField(blank=True, help_text='Antal dage før startdato denne opgave skal være færdig', null=True, verbose_name='Dage før start')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortering')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_entities', to='core.systemuser', verbose_name='Standard-ansvarlig')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='templates_mgmt.templateentity', verbose_name='Afhængigheder')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='entities.entity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_entities', to='templates_mgmt.onboardingtemplate')),
            ],
            options={
                'verbose_name': 'Skabelon-enhed',
                'verbose_name_plural': 'Skabelon-enheder',
                'ordering': ['sort_order'],
                'unique_together': {('template', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='TemplateEntityNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=True, verbose_name='Send email')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='In-app notifikation')),
                ('notify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_notification_rules', to='core.systemuser', verbose_name='Bruger')),
                ('template_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='templates_mgmt.templateentity')),
            ],
            options={
                'verbose_name': 'Notifikationsregel',
                'verbose_name_plural': 'Notifikationsregler',
                'unique_together': {('template_entity', 'notify_user')},
            },
        ),
    ]
