# Generated by Django 5.1.15 on 2026-02-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_systemuser_options_systemuser_auth_method_and_more'),
        ('templates_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateentitynotificationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='templateentitynotificationrule',
            name='notify_assignee',
            field=models.BooleanField(default=False, help_text='Send notifikation til den ansvarlige for opgaven', verbose_name='Notificer ansvarlig'),
        ),
        migrations.AddField(
            model_name='templateentitynotificationrule',
            name='trigger_status',
            field=models.CharField(choices=[('ready', 'Klar'), ('in_progress', 'I gang'), ('completed', 'Færdig'), ('skipped', 'Sprunget over')], default='completed', help_text='Send notifikation når opgaven skifter til denne status', max_length=20, verbose_name='Ved status'),
        ),
        migrations.AlterField(
            model_name='templateentitynotificationrule',
            name='notify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_notification_rules', to='core.systemuser', verbose_name='Bruger'),
        ),
    ]
