# Generated by Django 5.1.15 on 2026-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_mgmt', '0002_notification_rules_trigger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateentitynotificationrule',
            name='notify_dependent_assignees',
            field=models.BooleanField(default=False, help_text='Send notifikation til ansvarlige for opgaver der er direkte afhængige af denne', verbose_name='Notificer afhængige ansvarlige'),
        ),
    ]
