# Generated by Django 5.1.15 on 2026-02-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_completed', 'Opgave færdig'), ('task_assigned', 'Opgave tildelt'), ('task_ready', 'Opgave klar'), ('task_overdue', 'Opgave forsinket'), ('onboarding_completed', 'Onboarding færdig')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Besked')),
                ('is_read', models.BooleanField(default=False, verbose_name='Læst')),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.systemuser', verbose_name='Modtager')),
                ('related_onboarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingprocess')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtask')),
            ],
            options={
                'verbose_name': 'Notifikation',
                'verbose_name_plural': 'Notifikationer',
                'ordering': ['-created_at'],
            },
        ),
    ]
